#!/bin/sh
yq -Yi '(.spec.params[] | select(.name == "GIT_REPO").value) |="https://github.com/maximilianoPizarro/jhipster-vue-application"' pipeline-run.yaml
yq -Yi '(.spec.params[] | select(.name == "APP_JAR_VERSION").value) |="jhipster-vue-application-0.0.1-SNAPSHOT.jar"' pipeline-run.yaml
